
services:
  db:
    container_name: techscribe_database  # Set the container name
    image: postgres:latest  # Use the latest PostgreSQL image
    ports:
      - "5432:5432"  # Map port 5432 of the container to port 5433 on the host
    environment:
      POSTGRES_USER: nikhilenigma  # Set the PostgreSQL user
      POSTGRES_PASSWORD: root@123  # Set the PostgreSQL password
      POSTGRES_DB: techscribe  # Create a database
    volumes:
      - ./techscribe_data:/var/lib/postgresql/data  # Mount the host directory to persist data

volumes:
  code_mingle_data:  # Define the volume for PostgreSQL data
