services:
    database:
        image: postgres:17 # Use PostgreSQL 17 image
        container_name: nodedrafts_pg_container # Set the container name
        ports:
            - '${POSTGRES_PORT}:5432' # Map PostgreSQL port 
        environment:
            POSTGRES_USER: ${POSTGRES_USER} # Set the PostgreSQL user
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Set the PostgreSQL password
            POSTGRES_DB: ${POSTGRES_DB} # Create a database
        volumes:
            - postgres_data:/var/lib/postgresql/data # Mount the volume for persistent data

volumes:
    postgres_data:
        driver: local
